# Generated by Django 4.1.1 on 2022-09-23 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Correos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre Completo:')),
                ('email', models.EmailField(max_length=250, verbose_name='Email:')),
                ('mensaje', models.CharField(max_length=250, verbose_name='Mensaje:')),
                ('leido', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Correo',
                'verbose_name_plural': 'Correos',
            },
        ),
    ]
