# Generated by Django 4.1.1 on 2022-09-23 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0002_correos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correos',
            name='leido',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
