# Generated by Django 4.1.1 on 2022-09-23 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0003_alter_correos_leido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correos',
            name='mensaje',
            field=models.TextField(max_length=250, verbose_name='Mensaje:'),
        ),
    ]
